branch-defaults:
  MOODLE_403_STABLE:
    environment: AdaptEdtech-env
environment-defaults:
  AdaptEdtech-env-1:
    branch: null
    repository: null
global:
  application_name: AdaptEdtech
  default_ec2_keyname: aws-eb
  default_platform: PHP 8.2 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
