branch-defaults:
  KavaEdu:
    environment: KavaEdu-lms
global:
  application_name: KavaEdu
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 8.4 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: AdaptLiviu
  repository: null
  sc: git
  workspace_type: Application
